apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pay
  namespace: exam2
  labels:
    app: app-pay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-pay
  template:
    metadata:
      labels:
        app: app-pay
    spec:
      containers:
      - name: app-pay
        image: stigma137/app-pay:latest
        ports:
        - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
 name: app-pay
 namespace: exam2
 labels:
  app: app-pay
spec:
 selector:
  app: app-pay
 ports:
  - protocol: TCP
    port: 8010
    targetPort: 8010
    name: http