apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
kind: Service
apiVersion: v1
metadata:
  name: config-nodeport-service
spec:
  type: NodePort
  selector:
    app: config-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: config-app
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 2
  selector:
    matchLabels:
      app: config-app
  template:
    metadata:
      labels:
        app: config-app
    spec:
      containers:
      - name: config-app
        image: anamvgd/app-config:parcial-2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: config-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888